name: money_grower
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  firebase_storage: ^3.0.6
  cloud_firestore: ^0.12.9+5
  flutter_slidable: ^0.5.4
  async_loader: ^0.1.1
  rxdart: ^0.22.6
  cupertino_icons: ^0.1.2
  sprintf: ^4.0.0
  intl: ^0.15.5
  month_picker_strip: ^0.0.3
  datetime_picker_formfield: ^0.4.3
  charts_flutter: ^0.8.1
  random_color: ^1.0.3
  percent_indicator: ^2.1.1+1
  progress_indicators: ^0.1.4
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.0.14
  flutter_auth_buttons: ^0.6.0
  modal_progress_hud: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
